
# Spacecraft Reentry Simulation Configuration


# Parameters for the space craft thats reentering
spacecraft:

  initial_state:
    position: [6771000, 0, 0]
    velocity: [0, 3070, 0]

  design_parameters:
    drag_coefficient: 0.275  
    cross_sectional_area: 1 # meter squared
    mass: 100   # kg

# Parameters of the planet Earth
planet:
  mass: 5.972e24 # kg
  radius: 6371000 # meters

  atmosphere:
    atmospheric_density_model: "exponential_decay" # the only model implemented at the moment.
    sea_level_density: 1.225  # kilogram/meters^3
    scale_height: 15000 # meters

# Simulation control parameters
simulation:

  # Time settings
  start_time: 0  # seconds
  end_time: 1000  # seconds
  time_step_size: 100  # seconds

  # Need to implement these options and parameters for the integrator into my code eventually.
  integrator: 
    type: "RK4"
    relative_tolerance: 1.0e-6
    absolute_tolerance: 1.0e-8
    max_step_attempts: 10

  physics:
    gravity_model: "point_mass"
    include_drag: True
    include_lift: False  # not implemented yet
    include_heating: False #  "    "
    include_coriolis: False # "    "

  output:
    save_frequency: 10